# Note: this is a shared pipeline used by other repositories.
# Docs: https://docs.github.com/en/actions/using-workflows/reusing-workflows

on:
  workflow_call:
    inputs:
      installDependencies:
        type: boolean
        default: false
      preCommit:
        type: string
        required: false
      packageManager:
        type: string
        required: false
        default: yarn
      nodeVersion:
        required: false
        type: number
        default: 18
      appId:
        type: string
        required: false
    secrets:
      githubToken:
        required: false
      privateKey:
        required: false

jobs:
  changeset:
    runs-on: ubuntu-22.04
    if: github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - name: Generate a token
        if: ${{ inputs.appId }}
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ inputs.appId }}
          private-key: ${{ secrets.privateKey }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token || secrets.githubToken }}

      - uses: darkbasic/shared-config/setup@main
        name: setup env and install dependencies
        if: ${{ inputs.installDependencies }}
        with:
          nodeVersion: ${{ inputs.nodeVersion }}
          packageManager: ${{ inputs.packageManager }}

      - name: Create/Update Changesets
        uses: the-guild-org/changesets-dependencies-action@main
        with:
          preCommit: ${{ inputs.preCommit }}
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token || secrets.githubToken }}
